### ISSUE TITLE
[BUG] Deno/Fresh: Invalid type passed to createElement(): [object Object]

### ISSUE THREAD

**Issue by crummy** [petyosi/react-virtuoso#1154]
**Describe the bug**

When React Virtuoso is used in a Fresh project (Deno's web framework), the following error appears during render:
```
Invalid type passed to createElement(): [object Object]
```

**To Reproduce**

1. Install Deno
2. Run `deno run -A -r https://fresh.deno.dev` to create a Fresh project.
    * Skip styling and skip VS code setup.
3. Edit `islands/Counter.tsx` and the following line in the div:
    `<Virtuoso style={{ height: '400px' }} totalCount={200} itemContent={index => <div>Item {index}</div>} />`
4. Run `deno task start`
5. The web browser and console both report this error:
```
An error occurred during route handling or page rendering.
Error: Invalid type passed to createElement(): [object Object]
    at a.__b (https://esm.sh/stable/preact@10.22.0/denonext/debug.js:23:9)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2611)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2543)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:5050)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2543)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:3802)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:2543)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:5050)
    at m (https://esm.sh/v135/preact-render-to-string@6.3.1/X-ZS8q/denonext/preact-render-to-string.mjs:2:5050)
```

**Expected behavior**

The standard Fresh project appears, with a Virtuoso component.

**Desktop (please complete the following information):**

 - OS: MacOS 14.7
 - Browser: Chrome 130
 - Deno 2.0.0
 - Dependency versions:
 ```
     "$fresh/": "https://deno.land/x/fresh@1.7.3/",
    "$std/": "https://deno.land/std@0.216.0/",
    "@preact/signals": "https://esm.sh/*@preact/signals@1.2.2",
    "@preact/signals-core": "https://esm.sh/*@preact/signals-core@1.5.1",
    "preact": "https://esm.sh/preact@10.22.0",
    "preact/": "https://esm.sh/preact@10.22.0/",
    "react-virtuoso": "npm:react-virtuoso@^4.12.0"
```

**Additional context**

I know this might be a low-priority fix (maybe this bug should be against Fresh or Deno instead?) but wanted to get this documented in case someone else runs up against this in future.

**Comment by petyosi** [comment]
Looking at the stack trace, my guess would be something related to Preact itself. I don't believe Deno can affect the client-side. You can try to bring this to the Preact repo I guess. Happy to accept a PR. 

I'm closing this as it's extremely unlikely for me to engage with it, and I don't want to pile up open stuff.
